### root api
GET http://localhost:8000/

### Get all task
GET http://localhost:8000/api/v1/task/6473f1ca3b4a5ebd235b5a46

### insert task
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "Dancing",
    "hr": 100,
    "type": "entry"
}

### update task
PATCH  http://localhost:8000/api/v1/task
Content-Type: application/json

{
   "_id": "6473f1ca3b4a5ebd235b5a46",
    "type": "bad"
}

### Delete task
DELETE  http://localhost:8000/api/v1/task
Content-Type: application/json

{
  "ids": [
    "6473f1ca3b4a5ebd235b5a46"
  ]
}
